# Task configuration file: define virtual environment python path and script for each task type
fractal:
  venv_python: python
  script_path: scripts/run_fractal.py
primes:
  venv_python: python
  script_path: scripts/run_primes.py
sparams:
  venv_python: python
  script_path: scripts/run_sparams.py
microstrip:
  venv_python: python
  script_path: scripts/run_microstrip.py
