venv_python: python
script: runner.py
parameters:
  aedb_zip:
    label: AEDB Zip
    type: file
  xlsx:
    label: Stackup Excel
    type: file
  version:
    label: AEDT Version
    type: select
    options:
      "2024.1": "2024.1"
      "2024.2": "2024.2"
      "2025.1": "2025.1"
      "2025.2": "2025.2"
    default: "2025.1"
result_keep:
  - updated_aedb.zip
