venv_python: python
script: runner.py
parameters:
  brd:
    label: BRD File
    type: file
  edbversion:
    label: PyEDB Version
    type: select
    options:
      "2024.1": "2024.1"
      "2024.2": "2024.2"
      "2025.1": "2025.1"
      "2025.2": "2025.2"
    default: "2025.1"
result_keep:
  - board_aedb.zip
  - stackup.xlsx
